FROM python:alpine3.7
WORKDIR /app

COPY index.py requirements.txt ./

RUN pip install -r requirements.txt
EXPOSE 5000

ENV MQTT_DEFAULT_CONFIG=/etc/gateway/mqtt-config.json \
    UI_SRC_PATH=/app/uiplugin


# copy scripts and bootstrapper
COPY ./bootstrapper ./bootstrapper/
COPY ./scripts ./scripts/
COPY ./uiplugin ./uiplugin/

# On first start deploy the config-ui and on shutdown remove config-ui this is also done inside the entrypoint script
ENTRYPOINT ["scripts/entrypoint.sh"]